### ISSUE TITLE
Version conflicts in the latest snap release

### ISSUE THREAD

**Issue by tcuthbert** [snapcrafters/sentry#29] opened 2020-03-05 09:00 UTC
Hi,

Since yesterday our sentry environment has gone down with the web daemon failing to come online. The logs are filled with

```
sentry.web[21907]: Failed to load plugin 'sessionstack':
sentry.web[21907]: Traceback (most recent call last):
sentry.web[21907]:   File "/snap/sentry/79/lib/python2.7/site-packages/sentry/runner/initializer.py", line 25, in register_plugins
sentry.web[21907]:     plugin = ep.load()
sentry.web[21907]:   File "/snap/sentry/79/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2442, in load
sentry.web[21907]:     self.require(*args, **kwargs)
sentry.web[21907]:   File "/snap/sentry/79/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2465, in require
sentry.web[21907]:     items = working_set.resolve(reqs, env, installer, extras=self.extras)
sentry.web[21907]:   File "/snap/sentry/79/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
sentry.web[21907]:     raise VersionConflict(dist, req).with_context(dependent_req)
sentry.web[21907]: VersionConflict: (python3-saml 1.9.0 (/snap/sentry/79/lib/python2.7/site-packages), Requirement.parse('python3-saml<1.5,>=1.4.0')
```

The sentry 10 metadata file specifies python3-saml must be less than 1.5 but 1.9 is installed.

```./sentry-10.0.0.dist-info/METADATA:Requires-Dist: python3-saml (<1.5,>=1.4.0)```

**Comment by axinojolais** [comment] 2020-03-06 13:31
Maybe use a new track for Sentry v10 ?

**Comment by axinojolais** [comment] 2020-03-20 10:32
Ping @jamesbeedy :)

**Comment by mysiar** [comment] 2020-05-27 12:40
did any body managed to install `sudo snap install sentry --edge` ?
If so what os ?
The problem is to install `python3-saml==1.4.1`

**Comment by axinojolais** [comment] 2020-05-27 12:56
@mysiar no, edge still isn't fixed as far as I know

**Comment by ZuSe** [comment] 2020-10-08 09:31
Any news on that?

**Comment by saschanos** [comment] 2020-11-26 23:41
Looks like we need to switch to docker, right? :(

**Comment by hloeung** [comment] 2021-03-09 03:12
@popey, any chance you could take a look at this?

**Comment by popey** [comment] 2021-03-12 14:47
There's a fresh new build of sentry in the edge channel for amd64 architecture. Any brave souls fancy taking it for a spin? Sorry for the delay, it's been a bit of a pain to update.

**Comment by merlijn-sebrechts** [comment] 2022-11-15 10:39
Closing this issue as it seems to be fixed now.

**Closed as completed by merlijn-sebrechts** 2022-11-15 10:39 UTC
